#!/bin/bash

# Remove GoogleGearsSafari.
echo "Removing GoogleGearsSafari..."

# Remove Safari Plug-in
echo "Removing Plug-in..."
rm -rf "/Library/Internet Plug-Ins/Gears.plugin"

# Remove Input Manager
echo "Removing InputManager..."
rm -rf "/Library/InputManagers/GoogleGearsEnabler"

# Remove data base
echo "Removing Database..."
rm -rf ~/"Library/Application Support/Google/Google Gears for Safari"

# Removing this bundle
echo "Removing Uninstaller..."
rm -rf "/Library/Google/Google Gears"

# Done
echo "Done."
