// Copyright 2008, Google Inc.
//
// Redistribution and use in source and binary forms, with or without 
// modification, are permitted provided that the following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice, 
//     this list of conditions and the following disclaimer.
//  2. Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//  3. Neither the name of Google Inc. nor the names of its contributors may be
//     used to endorse or promote products derived from this software without
//     specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
// EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#include "base_interface_ff.idl"

[scriptable, uuid(3D32D95C-AC6D-11DC-8314-0800200C9A66)]
interface GearsBlobInterface : GearsBaseClassInterface {
  readonly attribute PRInt64 length;

  // Returns a blob that represents a subset of the current blob, beginning
  // at offset, and continuing for length bytes.  If length is omitted, the
  // slice continues to the end of the original blob.
  GearsBlobInterface slice(// in PRInt64 offset
                           // OPTIONAL in PRInt64 length
                           );
};

interface BlobInterface; // defined in C++
[ptr] native BlobInterfacePtr(const BlobInterface);

[/*NOT scriptable*/ uuid(F124EFB4-7CC9-4B92-8139-BE8AAE840F72)]
interface GearsBlobPvtInterface : nsISupports {
  [noscript] readonly attribute BlobInterfacePtr contents;
};
